#!/nix/store/6ph0zypyfc09fw6hlc1ygjvk2hv4j9vd-bash-5.3p3/bin/bash
set -e

/nix/store/w4i32hvrm6aic8hvnv9p4xkipcdykqjb-openresolv-3.17.0/bin/resolvconf -u
chgrp resolvconf /etc/resolv.conf
chmod g=u /etc/resolv.conf
/nix/store/gk6yfk5pxpy3gm17msmr4zk5b4warbv0-acl-2.3.2-bin/bin/setfacl -R \
  -m group:resolvconf:rwx \
  -m default:group:resolvconf:rwx \
  /run/resolvconf


